arm:
  type: ur10
sensors:
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [1.20, 3.40, 1.56]
      rpy: ['-pi/2', 1.32, 0]

  break_beam:
    type: break_beam
    pose:
      xyz: [1.60, 0.2, 0.91]
      rpy: [0, 0, 'pi']

  laser_profiler:
    type: laser_profiler
    pose:
      xyz: [1.60, 1.0, 0.85]
      rpy: [0, 0, 'pi']